name: sutt_task_aryan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^2.5.5
  google_sign_in: ^6.1.3
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  http: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  dio: ^5.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^2.0.0
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
