// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLo70qkJmTPAl5zGNfE8u9dZGN8DqWL8',
    appId: '1:774731589854:web:e633fffa0ccb9e360fba4f',
    messagingSenderId: '774731589854',
    projectId: 'sutt-task-aryan',
    authDomain: 'sutt-task-aryan.firebaseapp.com',
    storageBucket: 'sutt-task-aryan.appspot.com',
    measurementId: 'G-JZJVN4DZFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpaX24LjUioCOWe9b8GTyMYYmHyEmH-Ro',
    appId: '1:774731589854:android:d76df9488094835a0fba4f',
    messagingSenderId: '774731589854',
    projectId: 'sutt-task-aryan',
    storageBucket: 'sutt-task-aryan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCearvC5LNl9UkRyziS4MhcrSJBdY3f9Vs',
    appId: '1:774731589854:ios:5bed6ad1f16f01130fba4f',
    messagingSenderId: '774731589854',
    projectId: 'sutt-task-aryan',
    storageBucket: 'sutt-task-aryan.appspot.com',
    androidClientId: '774731589854-jiesmej9d6tjee182rvg7o2ns936htdr.apps.googleusercontent.com',
    iosClientId: '774731589854-rhc1k3nh24qd6oddko0aij19rifcabns.apps.googleusercontent.com',
    iosBundleId: 'com.aryan.gupta.suttTaskAryan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCearvC5LNl9UkRyziS4MhcrSJBdY3f9Vs',
    appId: '1:774731589854:ios:5bed6ad1f16f01130fba4f',
    messagingSenderId: '774731589854',
    projectId: 'sutt-task-aryan',
    storageBucket: 'sutt-task-aryan.appspot.com',
    androidClientId: '774731589854-jiesmej9d6tjee182rvg7o2ns936htdr.apps.googleusercontent.com',
    iosClientId: '774731589854-rhc1k3nh24qd6oddko0aij19rifcabns.apps.googleusercontent.com',
    iosBundleId: 'com.aryan.gupta.suttTaskAryan',
  );
}
